USE [master]
GO

/****** Object:  Database [RezaSuperMarket]    Script Date: 3/3/2021 10:50:44 AM ******/
CREATE DATABASE [RezaSuperMarket]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RezaSuperMarket', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RezaSuperMarket.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RezaSuperMarket_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RezaSuperMarket_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RezaSuperMarket].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RezaSuperMarket] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RezaSuperMarket] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RezaSuperMarket] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RezaSuperMarket] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RezaSuperMarket] SET ARITHABORT OFF 
GO

ALTER DATABASE [RezaSuperMarket] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RezaSuperMarket] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RezaSuperMarket] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RezaSuperMarket] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RezaSuperMarket] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RezaSuperMarket] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RezaSuperMarket] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RezaSuperMarket] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RezaSuperMarket] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RezaSuperMarket] SET  ENABLE_BROKER 
GO

ALTER DATABASE [RezaSuperMarket] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RezaSuperMarket] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RezaSuperMarket] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RezaSuperMarket] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RezaSuperMarket] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RezaSuperMarket] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [RezaSuperMarket] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RezaSuperMarket] SET RECOVERY FULL 
GO

ALTER DATABASE [RezaSuperMarket] SET  MULTI_USER 
GO

ALTER DATABASE [RezaSuperMarket] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RezaSuperMarket] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RezaSuperMarket] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RezaSuperMarket] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RezaSuperMarket] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RezaSuperMarket] SET QUERY_STORE = OFF
GO

ALTER DATABASE [RezaSuperMarket] SET  READ_WRITE 
GO

